version: '2.1'
orbs:
  cypress: cypress-io/cypress@3
executors:
  node-version: '14.17.6'
workflows:
  use-my-orb:
    jobs:
      - cypress/run:
          package-manager: yarn
          start-command: yarn start