version: '2.1'
orbs:
  cypress: cypress-io/cypress@3
jobs:
  run-tests:
    executor: cypress/base:14.17.6
    steps:
      - checkout
      - cypress/run:
          package-manager: yarn
          start-command: yarn start
workflows:
  use-my-orb:
    jobs:
      - run-tests
      