version: '2.1'
orbs:
  cypress: cypress-io/cypress@3
jobs:
  install-node:
    docker:
      - image: cimg/node:14.17.6
    steps:
      - checkout
      - run: node --version
workflows:
  use-my-orb:
    jobs:
      - install-node:
          name: Install node
      - cypress/run:
          package-manager: yarn
          start-command: yarn start
          parallelism: 2
          requires:
            - Install node