version: '2.1'
orbs:
  cypress: cypress-io/cypress@3
jobs:
  install:
    executor: cypress/base:14.17.6
    steps:
      - cypress/install:
          install-browsers: false
      - persist_to_workspace:
          root: ~/
          paths:
            - .cache/Cypress
            - project
  run-tests:
    executor: cypress/base:14.17.6
    parallelism: 10
    steps:
      - run: echo "This step assumes dependencies were installed using the cypress/install job"
      - attach_workspace:
          at: ~/
      - cypress/run-tests:
          cypress-command: 'yarn cypress run --parallel --record'
          start-command: 'yarn start'
workflows:
  use-my-orb:
    jobs:
      - install
      - run-tests
      