version: '2.1'
orbs:
  node: circleci/node@4.7
  cypress: cypress-io/cypress@3
jobs:
  install-node-example:
    steps:
      - node/install:
          node-version: '14.17.6'
          install-yarn: true
workflows:
  use-my-orb:
    jobs:
      - cypress/run:
          package-manager: yarn
          start-command: yarn start
          parallelism: 2