version: '2.1'
orbs:
  cypress: cypress-io/cypress@3
executors:
  with-chrome:
    resource_class: small
    docker:
      - image: "cypress/browsers:node14.17.6-chrome100-ff98"
workflows:
  use-my-orb:
    jobs:
      - cypress/install:
          executor: with-chrome
      - cypress/run:
          package-manager: yarn
          start-command: yarn start
          parallelism: 2