version: '2.1'
orbs:
  cypress: cypress-io/cypress@2
workflows:
  use-my-orb:
    jobs:
      - cypress/install
      - cypress/run:
          requires:
            - cypress/install
      yarn: true
      start: yarn start
      executor: cypress/browsers:node14.17.6-slim-chrome100-ff99-edge
      browser: chrome
      parallel: true
            parallelism: 4
      record: true
      group: 4 machines