name: Cypress Tests
on: [push]
env:
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PORTAL_URL: ${{ secrets.PORTAL_URL }}
  QUERY_API_URL: ${{ secrets.QUERY_API_URL }}
  LOGIN_API_URL: ${{ secrets.LOGIN_API_URL }}
  LOGIN_API_KEY: ${{ secrets.LOGIN_API_KEY }}
  LOGIN_SECRET_KEY: ${{ secrets.LOGIN_SECRET_KEY }}
  GRAPHCMS_ENDPOINT: ${{ secrets.GRAPHCMS_ENDPOINT }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  TWELVE_LABOURS_XML: ${{ secrets.TWELVE_LABOURS_XML }}
  FLATMAP_API: ${{ secrets.FLATMAP_API }}
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: List of the GitHub Actions environment variables
        run: env
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.17.6
      - name: Cypress install
        uses: cypress-io/github-action@v5
        with:
          runTests: false
          build: yarn build
      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: build-folders
          if-no-files-found: error
          path: .nuxt/dist
  e2e-testing:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: List of the GitHub Actions environment variables
        run: env
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.17.6
      - name: Download the build folders
        uses: actions/download-artifact@v3
        with:
          name: build-folders
          if-no-files-found: error
          path: ./
      - name: Run e2e tests
        uses: cypress-io/github-action@v5
        with:
          build: yarn build
          start: yarn start
          wait-on: 'http://localhost:3000'
          command: yarn test-e2e-ci
          